# Generated by Django 4.2.7 on 2025-11-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_subscription_storage_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly Plan"),
                    ("annual", "Annual Plan"),
                    ("oneday", "OneDay Plan"),
                ],
                max_length=20,
            ),
        ),
    ]
